### ISSUE TITLE
not pip installabe

### ISSUE THREAD

**Issue by hmsaleem** [Edilmo/brat-widget#1]
```
$ pip install brat_widget
Collecting brat_widget
  Could not find a version that satisfies the requirement brat_widget (from versions: )
No matching distribution found for brat_widget
```

**Comment by Edilmo** [comment]
Hi @elric-dev , the widget is still under development. That's why it's still not available through pip.
If you want to give it a try, you can follow the steps in the readme which indicate how to prepare the development environment. I just updated those steps. Let me know any comments.

**Comment by hmsaleem** [comment]
Thanks! Really exciting widget and much needed!

**Comment by johann-petrak** [comment]
Is there a plan for making it pip installable or has this project died? (the last comment in this issue is from 2017)
I am looking for the functionality this seems to provide as a dependency for a nlp-related library, but unless it is pip installable there is no way to consider a package.
